// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeO3ce9VEFxL046aBcdclQAAzEuRO0XFU',
    appId: '1:348616930740:web:01f4a91a1133dbfe716ee1',
    messagingSenderId: '348616930740',
    projectId: 'taskmanager-a79f7',
    authDomain: 'taskmanager-a79f7.firebaseapp.com',
    storageBucket: 'taskmanager-a79f7.firebasestorage.app',
    measurementId: 'G-9W64CQBH08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyYWdvTBTX7zgKITvRhJJcEtAp8Zb2wI',
    appId: '1:348616930740:android:b9afb5e4574f0cf0716ee1',
    messagingSenderId: '348616930740',
    projectId: 'taskmanager-a79f7',
    storageBucket: 'taskmanager-a79f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDmbylvdAnQSg0-HG2WXuc4V4vvmjg0Q',
    appId: '1:348616930740:ios:6e62e45c846426d9716ee1',
    messagingSenderId: '348616930740',
    projectId: 'taskmanager-a79f7',
    storageBucket: 'taskmanager-a79f7.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWDmbylvdAnQSg0-HG2WXuc4V4vvmjg0Q',
    appId: '1:348616930740:ios:6e62e45c846426d9716ee1',
    messagingSenderId: '348616930740',
    projectId: 'taskmanager-a79f7',
    storageBucket: 'taskmanager-a79f7.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeO3ce9VEFxL046aBcdclQAAzEuRO0XFU',
    appId: '1:348616930740:web:1bb5d8fb3d810354716ee1',
    messagingSenderId: '348616930740',
    projectId: 'taskmanager-a79f7',
    authDomain: 'taskmanager-a79f7.firebaseapp.com',
    storageBucket: 'taskmanager-a79f7.firebasestorage.app',
    measurementId: 'G-VY8FLVSJZ7',
  );
}
